FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# BucketList-API
This is a bucket list API built on [Flask](http://flask.pocoo.org/).

This feature rich API requires token based authentication to access resources.
It also has pagination and search capabilities on the resources requested.


The features attached to the service include: 
* authenticating a user
* creating new bucketlist items
* updating and deleting the items 
* retrieving a list of all created bucket lists by a registered user.


## User Authentication 

### Registration [/auth/register/]
### Register a new user [POST]
You may use any name or password combination for the registration.

+ Request (application/json)

        {
            "username": "Lana",
            "password": "Kane"
        }
        
+ Response 201 (application/json)
    
        {
            "message": "User Lana has successfully been registered"
        }

### Login [/auth/login/]
### Log in a user [POST]

Use your correct password and username cobination to verify your identity.
Do take note of the token returned on successful login as it will be required
to access other resources.

+ Request (application/json)

        {
            "username": "Lana",
            "password": "Kane"
        }
        
+ Response 200 (application/json)

        {
            "token": "Som3Rand0mTok3n"
        }

## Group Resources

### Bucketlist Resources [/bucketlists/]

### Create a new bucketlist [POST]
Add a new bucketlist to your to-dos

+ Request (application/json)
    
    + Headers
        
            Authorization: JWT Token
    
    + Body

            {
                "list_name": "Bae for Kiki"
            }
            
+ Response 200 (application/json)
    
        {
            "creator": "1",
            "id": 1,
            "list_name": "Bae for Kiki",
            "date_created": "Wed, 17 Feb 2016 12:14:33 -0000",
            "date_modified": "Wed, 17 Feb 2016 12:14:33 -0000",
            "items": []
        }

+ Response 400 (application/json)

        {
            "message": "There was an error while trying to create your resource"
        }